name: Node.js CI

on:
  push:
    paths:
      - 'applications/digital-wallet-app/**'
      - 'applications/admin-ui/**'
      - '.github/workflows/node-ci.yml'
  pull_request:
    paths:
      - 'applications/digital-wallet-app/**'
      - 'applications/admin-ui/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [digital-wallet-app, admin-ui]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & Test
        run: |
          cd applications/${{ matrix.app }}
          npm install
          npm run build --if-present
          npm test --if-present